### ISSUE TITLE
Doesnt deploy

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#154]
![2017-08-26 2](https://user-images.githubusercontent.com/26114104/29728927-a203356a-89f7-11e7-926a-e06c79fdacfc.png)
![2017-08-26 1](https://user-images.githubusercontent.com/26114104/29728928-a205eb84-89f7-11e7-9a9f-fa8951f63d73.png)
![2017-08-26](https://user-images.githubusercontent.com/26114104/29728929-a20718b0-89f7-11e7-9534-2f45ced55214.png)

**Comment by avaer** [comment]
Deploys now!
