### ISSUE TITLE
Ground Rendering Problem

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#156]
![2017-08-31 3](https://user-images.githubusercontent.com/26114104/29909512-de1ecbb8-8e43-11e7-9cac-a838ec1f1d42.png)

Doesn't render when you go out of range and come back to it.

**Comment by avaer** [comment]
Might be related to flying into the sky.

```
worker.js:2115 Uncaught TypeError: Cannot destructure property `offset` of 'undefined' or 'null'.
    at _getCull (worker.js:2115)
    at self.onmessage.e (worker.js:2334)
```

**Comment by avaer** [comment]
Possibly fixed with https://github.com/modulesio/zeo/commit/7b333fbb40507b3b5cd1e90500af2b2a8a5d0a83.

**Comment by avaer** [comment]
Will re-open if it persists.
