### ISSUE TITLE
Menu Issue

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#157]
![2017-08-31 1](https://user-images.githubusercontent.com/26114104/29909705-c5103d5e-8e44-11e7-8842-55fab0947398.png)
![2017-08-31 2](https://user-images.githubusercontent.com/26114104/29909706-c519f7ae-8e44-11e7-8e66-ab9d8f5fe453.png)

Doesnt switch to mods tab & Doesnt go back from entity tab to entity list.

**Comment by avaer** [comment]
I think this is probably the generation holding up the server rendering through to Chrome. i.e. dupe of https://github.com/modulesio/zeo/issues/169
