### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by PeteBoucher** [exokitxr/zeo#158]
After invoking `docker run -p 8000:8000 modulesio/zeo` in the zeo folder for the first time on Mac OS 10.10.5, Docker version 17.07.0-ce I get the following error:
```
yarn add v0.0.5
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ skin@0.0.1
warning No license field
Done in 0.72s.
/root/zeo/installed/plugins/_plugins_heightfield/node_modules/heightfield/generator.js:685
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/zeo/installed/plugins/_plugins_heightfield/node_modules/heightfield/server.js:18:22)

```

**Comment by avaer** [comment]
Thanks for this!

Been neglecting the Docker builds and a trailing comma broke `node 7` in the `Dockerfile`. There's still a ton of things in flux but it should at least boot on Docker again:

```docker pull modulesio/zeo```

to get the new image once it builds. Please reopen if it still doesn't boot for you!

**Comment by PeteBoucher** [comment]
Thanks for the quick fix, server starts now but Chrome fails
```
➜  zeo git:(master) ✗ docker run -p 8000:8000 modulesio/zeo

> zeo@0.0.1 start /root/zeo
> scripts/standalone.sh

~/zeo ~/zeo
Warning: failed to open UPnP port: timeout
You might need to configure your router to forward port 8000.
warning: Could not start Chrome. Using *slow* local rendering; VR clients will experience hitching. To fix this, install Chrome.
Server: http://127.0.0.1:8000/
```
I'm on Mac OS 10.10.5 and have
Crome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by avaer** [comment]
Yeah that's a known issue; the Docker image does not contain Chrome. It should still work, but UI's will hitch on rasterizing HTML. Unfortunately the browser still does not support doing this asynchronously, and it's hard to get it done at 90FPS without this hack.

Either we need to
- add a copy of Chrome to the Docker build (PR appreciated), or
- not use Docker, allowing native Chrome to be used (how I'm developing). But this has security tradeoffs for hotloading VR modules from npm.

Added an issue for it at https://github.com/modulesio/zeo/issues/161.
