### ISSUE TITLE
Server crashed and failed to load assets on restarting

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#164]
![2017-09-24 1](https://user-images.githubusercontent.com/26114104/30780472-09d3d49a-a129-11e7-92c2-461ad73caf37.png)
![2017-09-24 2](https://user-images.githubusercontent.com/26114104/30780514-0be89e40-a12a-11e7-838c-3790755b8e0d.png)

![artboard 1](https://user-images.githubusercontent.com/26114104/30780475-09d598de-a129-11e7-905a-3d908d9e719f.png)
![2017-09-21 5](https://user-images.githubusercontent.com/26114104/30780474-09d58100-a129-11e7-9865-6587ff178d7c.png)

**Comment by avaer** [comment]
I think this was the same problem as https://github.com/modulesio/zeo/issues/170.
