### ISSUE TITLE
Parallelize procedural generation

### ISSUE THREAD

**Issue by avaer** [exokitxr/zeo#169]
## Background

The main server is a single-threaded node script. It starts at [`index.js`](https://github.com/modulesio/zeo/blob/master/index.js#L287), and then loads a ton of [mandatory core engines](https://github.com/modulesio/zeo/tree/master/core/engines), as well as [configurable and optional user plugins](https://github.com/modulesio/zeo/tree/master/plugins).

There are some first-party "core plugins" that generate the default voxel world. The core plugins are in [this defaults list](https://github.com/modulesio/zeo/blob/master/defaults/world/tags.json), and this issue is concerned with a small relevant subset of these plugins. These relevant ones are mostly:

[`generator`](https://github.com/modulesio/zeo/tree/master/plugins/generator)
[`heightfield`](https://github.com/modulesio/zeo/tree/master/plugins/heightfield)
[`grass`](https://github.com/modulesio/zeo/tree/master/plugins/grass)
[`object`](https://github.com/modulesio/zeo/tree/master/plugins/objects)

The `generator` mod in particular delegates most of its hard number-crunching work to the native C++ module `vxl`. That's over [here](https://github.com/modulesio/vxl), it's developed in-house, so we can totally change it if we need to. We publish that `vxl` module to `npm` and source it in the `random` utils engine [here](https://github.com/modulesio/zeo/blob/master/core/utils/random-utils/package.json#L11). And the `generator` plugin gets it from the random utils and uses it [here](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L54).

I haven't profiled this but I suspect that the major performance hog that ties up the event loop is this `vxl` module, being called from the [`generator` plugin's server.js](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js). This issue might not need to touch the `vxl` native module at all, but it's important to know what it does and why it's there.

## The problem

Basically the `vxl` module does its work synchronously in the main thread, so it hogs the event loop. We recently introduced this module for performance reasons and it's doing that job well -- it's fast -- however running its methods synchronously has the nasty side-effect of causing networking problems for multiplayer and the rest of the server's responsiveness in general.

While the event loop is hogged on number-crunching such as [these tesselations](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L136), we cannot [stream avatar positions in our websockets](https://github.com/modulesio/zeo/blob/master/core/engines/multiplayer/server.js#L164), or [stream mic audio](https://github.com/modulesio/zeo/blob/master/core/engines/voicechat/server.js#L67). And a bunch of other stuff.

The hogging might not be too bad by web server standards, but even something like 20 milliseconds time spent crunching the tesselation is a disaster for realtime streaming like we're doing. Position jitter, audio stutters, things like that are all caused by this synchronous code.

There is a related problem in that the generation plugins do other book-keeping stuff in the service of calling the `vxl` module and marshalling things to and fro. So this causes additional overhead by generating garbage/typed buffer copies on the main thread, and garbage collection pauses can further slow things down and make performance unreliable.

## What needs to be done

First, we should profile the backend while doing heavy world generation. I've been using the node debugging feature of Chrome to capture that profile, using something like [this](https://github.com/modulesio/zeo/blob/master/scripts/test-http.sh#L7). World generation happens when you navigate around the world -- we pull in new chunks of the world in realtime from the server to the client, where we render it as geometry. On the frontend we stream data in [here](https://github.com/modulesio/zeo/blob/master/plugins/generator/worker.js#L1144) and that hits the backend [here](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L736). This issue is concerned with the latter.

I'm not 100% sure what the current performance/event loop hog bottlenecks are, so _we should verify that first with profiles before jumping to conclusions_. However, I strongly suspect that these `vxl` world generation code paths are a major culprit that needs to change.

Luckily there is pretty much no reason calling the `vxl` methods needs to be in the path of the main loop. AFAIK all of the places we do that can use a worker process, or worker pool instead. If indeed the profile shows that the generation methods are holding up the loop, we should break out all of the places to stream results to/from a new lightweight worker process using some sort of IPC via `child_process.fork()` or similar.

The main challenge here would be marshalling/serializing data back and forth. There are a [*lot* of typed buffers](https://github.com/modulesio/zeo/blob/master/plugins/generator/objects-tesselator.js#L66) flying around for the different things we use in the world generation.

Luckily serializing these around is mostly _already_ a solved problem because we already needed to do it for streaming stuff to the client. You'll note that these procedural generation plugins already have their own [`protocol-utils.js`](https://github.com/modulesio/zeo/blob/master/plugins/generator/lib/utils/protocol-utils.js) which is what they use to shape the data for transfer on the wire using a single buffer. This can very likely be reused to serialize data between processes, by structuring the binary buffers on one end and parsing them back on the other.

We maybe _could_ use `JSON.stringify` for some serialization things, but in general it will not work well for these geometry/world generation buffers; they're too big (megabytes per second) and JSON stringification/base64/whatever can itself be a processor and/or garbage collection problem. Using structured binary buffers/typed arrays skips all of these problems, which is why the code uses that approach in `protocol-utils` instead of JSON, even though arguably JSON might be cleaner in an ideal world.

Another challenge might possibly be managing the actual world data while doing parallel work. We [save chunks to disk as they're generated](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L414) -- since the user can mutate them afterwards with different tools, we want them to persist across reboots. So that's one thing we can't really parallelize or have multiple copies of. That most likely _shouldn't_ be a performance problem/challenge since all of the writes here are asynchronous already, and this part of code does not do any meaningful number crunching work. But we gotta be careful that there is a central, controlled place we load/save chunks data, because if we try to truly parallelize this load/save it's easy to get into nasty corruption race conditions.

For clarification, [`zeode`](https://github.com/modulesio/zeode) is also our code and we can change it if needed. Its role is purely loading/saving/storage of chunks data using a bunch of typed buffers.

Finally, we should probably try to keep the number of workers small and centralized. In particular, I don't think it's a good idea to fork a new process for each task, because that adds up to its own overheads. Instead we should use some sort of worker pool. Maybe even a single worker owned by the `generator` plugin, which takes requests from all of the other plugins. This would be very in line with what the `generator` plugin is already doing, which is [acting like a world generation method hub](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L445) that the other plugins are already calling.

## Summary

So the order of operations for this issue seems like:
1. Profile to find out all of the methods/code points that are dominators in hogging the event loop that are getting in the way of making the server relatively transparent for streaming data across. There's no good reason to have any number crunching on the main loop, and the `vxl` calls are probably the main culprit. We should also look at what the garbage collector is doing, since GC pauses can also get in the way of realtime streaming.

1. Once profiled, figure out and implement a strategy, or better yet multiple smaller strategies, for breaking out the synchronous parts into something asynchronous. Best to do this work piecewise in as small PR's as possible, so they can be individually tested/verified. The code has a lot of moving pieces so it's good to ship pieces that slowly make the generation more asynchronous rather than shipping one enormous overhaul that does everything.

1. Go back and verify to see that the main performance/GC dominators are no longer the heavy hitters like `vxl` genertion method calls. At that point we might find other performance bottlenecks worth fixing.

## Addendum/trivia

- Might want to clear out `data/zeode.dat` when profiling and testing. That's the chunks data file, and [if it exists it will be loaded and used instead of generating the world](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L170). So if it's there on server startup, no (or at least less) generation will run or show up in the profile, therefore interfering with working on this issue.
- We could almost certainly gain a multiplier on real-world generation rate by parallelizing to multiple worker processes (= multithreading). That is not the main goal with this issue, but if we think ahead (i.e. make sure the worker process is not a singleton that assumes it's the only one) I think we can get that for "free" in a follow-up issue.
- [`archae`](https://github.com/modulesio/archae) is our npm module hotloader. It probably does not need to change, but it shows up a lot in stack traces in paths, so it might be helpful to know that.
- We compile `vxl` to `WebAssembly` and we also [use it on the frontend sometimes](https://github.com/modulesio/zeo/blob/master/plugins/generator/worker.js#L14), so terrain reshaping and other mutations do not need to go through the network. This probably doesn't need to be touched, but I'm noting it here so it's not surprising why it seems there is backend code seemingly called on the frontend. Because it kind of is! It's not the same bits running, but it is built from the same source code and loaded in both places.

**Comment by avaer** [comment]
Heavy server profile:

<img width="745" alt="capture" src="https://user-images.githubusercontent.com/6926057/31024921-967b72d4-a50e-11e7-8f28-b8aca1be844c.PNG">

Looks like the worst culprit is GC; 14% of clock time is spent there, and that's wasted work on top of the actual processing. This is probably all of the arraybuffers and typedarray views being created and discarded in the generator server. But it's hard to tell -- should find a way to get an allocation profile to confirm where all of this garbage is being allocated.

Also highlighted are the two main generator calls, [`_generateChunkTerrain`](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L114) and [`_generateChunkObjects`](https://github.com/modulesio/zeo/blob/master/plugins/generator/server.js#L118). In the former it looks like the worst hog is just initializing typed arrays, and in the latter it's various `vxl.noiser` methods.

**Comment by zoecarver** [comment]
I agree. Have you ever tried [`dtrace`](https://nodejs.org/en/blog/uncategorized/profiling-node-js/)? I have heard that it is good. Also, what is the garbage collector doing in this profile?

**Comment by avaer** [comment]
Either dtrace or chrome profiler are good.

The garbage collector here is doing no useful work. It's collecting JS objects that are not in scope. And since there's a lot of this that means the allocation rate is high somewhere.

Moving those allocations or thinking them out of the code woul fix that. And I wouldn't be surprised if the code that's allocating garbage is exactly the buffers code that keeps the event loop.

**Comment by zoecarver** [comment]
Alright, that makes sense. What should I do next? Should I work on a strategy for making sure that the garbage collector is only collecting JS objects that are in the scope? Or should I try to break the garbage collector into an asynchronous task?

**Comment by avaer** [comment]
Replied in Slack but for reference, we should do both -- get rid of the allocations by e.g. statically allocating in global scope, _and_ also try to move the allocations to a child process. The latter of which is a natural consequence of moving the `vxl` calls, since the buffers are tied up there.

**Comment by avaer** [comment]
Gonna tackle this.
