### ISSUE TITLE
Skin disappears when drawn out of wallet

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#182]
Symptom: 
1. Loaded Zeo, 
2. Pulled out skin from wallet
3. Looked down to drop it in bag
4. Disappeared from wallet (PFA Screenshot of wallet after)
![screenshot 51 _li](https://user-images.githubusercontent.com/26114104/31860715-2f54c304-b73c-11e7-8fce-d8cace032b99.jpg)

**Comment by avaer** [comment]
I think this one is fixed with the store refactor.
